### PR TITLE
fix for multivolume files

### PR DESCRIPTION
**Pull request by zubata88**
Only the spatial dimensions are necessary for the reorientation of the volume. If the full shape is used, this will only work for volumetric data, and wont work for multi volume files or volumetric timeseries.

### CODE REVIEW

**Comment by spezold** [comment]
Thanks for that! It will help with the issue of multiple data dimensions. Currently, however, it breaks assumptions (e.g. that the given data array for initializing a new Volume is three-dimensional) and functionality (the anatomical_coordinates.swap() function for aligning arrays to a coordinate system assumes that the given permutation matrix is defined for all rather than the first three dimensions). I will see if I can commit to your pull request branch and then continue working on it!

**Comment by spezold** [comment]
@zubata88 Now everything should be complete (at least regarding NIfTI files)

**Comment by zubata88** [comment]
nice, thanks!

**Comment by spezold** [comment]
I have to thank you!

**Pull request merged**
